name: php-apache-core
services:
  php-apache:
    image: dvc-wordpress:php-apache
    container_name: php-apache
    hostname: php-apache
    tty: true
    user: ${USER_UID:-1000}:${USER_GID:-1000}
    ports:
      - ${PHP_IP_PORT:-127.0.0.1:8080}:80
      - ${PHP_BUILT_IN_IP_PORT:-127.0.0.1:10080}:10080
    volumes:
      - php-apache-data:/var/www
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-../..}/php-apache
        target: /php-apache
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-../..}/workspace_share/
        target: /share/
      # dvc-wordpress:php-apache イメージで使う PHP や Apache2 の設定を変更したい場合は、必要なファイルを用意してから上記のバインドマウントを有効化

  php-apache-mysql:
    image: mysql:8.0.42-bookworm
    container_name: php-apache-mysql
    hostname: php-apache-mysql
    volumes:
      - php-apache-mysql-data:/var/lib/mysql
    ports:
      - ${MYSQL_IP_PORT:-127.0.0.1:13306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-php-apachepass001}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_USER=${MYSQL_USER:-dbuser001}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-dbpass001}
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"
      start_interval: 1s
      start_period: 10s
      timeout: 1s
      interval: 30s
      retries: 10

  php-apache-adminer:
    image: adminer:5.3.0-standalone
    container_name: php-apache-adminer
    hostname: php-apache-adminer
    ports:
      - ${ADMINER_IP_PORT:-127.0.0.1:5080}:8080
    environment:
      ADMINER_DEFAULT_SERVER: php-apache-mysql
    depends_on:
      php-apache-mysql:
        condition: service_healthy

volumes:
  php-apache-data:
    name: dvc-wordpress-php-apache-data
  php-apache-mysql-data:
    name: dvc-wordpress-php-apache-mysql-data
